### ISSUE TITLE
No repository found containing: osgi.bundle,org.slf4j.log4j,1.7.2.v20130115-1340

### ISSUE THREAD

**Issue by RBDurgin** [pmd/pmd-eclipse-plugin#124] opened 2020-06-19 00:24 UTC
Plugin doesn't seem to be installing in the latest version of Eclipse 2020-06. Receive the following error when installing from either the snapshot update site:

`An error occurred while collecting items to be installed
session context was:(profile=xxxxx_eclipse_java-2020-06_Eclipse.app_Contents_Eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.slf4j.log4j,1.7.2.v20130115-1340`

OS: MacOS Catalina 10.15.5

**Comment by adangel** [comment] 2020-06-21 16:34
@RBDurgin Thanks for reporting.
I've just tried to reproduce this, but can't. I used the following steps:
* Download Eclipse IDE for Java Developers from https://www.eclipse.org/downloads/packages/
* Install pmd-eclipse-plugin via the market place (Help :arrow_right: Eclipse Marketplace ...)

Note, I'm using Linux....

I see, that I have a plugin org.slf4j.log4j  installed now (it was not there before):

`	Eclipse.org	SLF4J Log4j implemented over SLF4J	1.7.2.v20130115-1340	org.slf4j.log4j`

I'll investigate further, why this is actually there - it should not be needed, since pmd-eclipse-plugin uses already slf4j directly (and should not need log4j anymore).

**Comment by adangel** [comment] 2020-06-21 17:05
So, we import the package `org.apache.log4j` (see https://github.com/pmd/pmd-eclipse-plugin/blob/bfbb34c40a3b26bc39d536528b0459198225d796/net.sourceforge.pmd.eclipse.plugin/META-INF/MANIFEST.MF#L174)

This is resolved via the extra repository orbit https://github.com/pmd/pmd-eclipse-plugin/blob/bfbb34c40a3b26bc39d536528b0459198225d796/net.sourceforge.pmd.eclipse.p2updatesite/category.xml#L11

There are at least two different plugins, that provide the package `org.apache.log4j`: "Apache Jakarta log4j Plug-in" and "SLF4J Log4j implemented over SLF4J". Eclipse obviously chose the latter.

I don't remember the exact reason, why I left this requirement when finishing #112. I see a commit there -> https://github.com/pmd/pmd-eclipse-plugin/pull/112/commits/8cf58668c2076885f4d03e86e4176cda869d480d

>
> *   Usage of Log4j is deprecated and is going to be removed. Logback via slf4j is replacing it.
>     Therefore the following methods/fields are deprecated for removal in `net.sourceforge.pmd.eclipse.runtime.preferences.IPreferences`:
>     *   `getLogLevel()`
>     *   `setLogLevel(Level)`
>     *   `LOG_LEVEL`
>

I need to see, if there is a different solution than using orbit while still maintaining compatibility

**Comment by adangel** [comment] 2020-06-21 17:41
I'm still have the fundamental problem, that I can't reproduce your exact case. Whatever I do, I would solve a different problem...

Do you have other plugins installed? Can you share your configuration? (Help :arrow_right: About Eclipse IDE :arrow_right: Installation Details :arrow_right: Configuration :arrow_right: Copy to clipboard)

**Comment by adangel** [comment] 2020-06-22 17:43
Maybe related / similar: #120

**Comment by adangel** [comment] 2020-06-26 16:52
I digged a little bit into the problem, and it's most likely a general eclipse problem.

I've noticed, that the orbit site for kepler has been archived, so I updated it. But that's probably not the real issue, because I've noticed the same error sometimes for the correct site, too.

There are the following workarounds:
*   Restart eclipse and try again. That helped for me. After restart, I've seen, that there are many more update sites in the preferences than before, so this points towards a concurrency issue.
*   Remove the orbit repository from update sites, restart eclipse, add it manually again https://archive.eclipse.org/tools/orbit/downloads/drops/R20140114142710/repository/
    and restart eclipse and then install PMD
*   Change the url in the update site (change from https to http or back, remove/add trailing slash, ...)
*   see https://stackoverflow.com/questions/6470802/what-to-do-about-eclipses-no-repository-found-containing-error-messages

The PR #126 will additionally include org.slf4j.log4j, so that this doesn't need to be downloaded from orbit anymore, which might already help.

**Closed** 2020-06-27 09:45 UTC
Labels: bug
