### ISSUE TITLE
Impossible to install properly PMD Plug-in 4.4.1.v20190602-1719 within  Eclipse 2018-12 (4.10.0) Build id : 20181214-0600

### ISSUE THREAD

**Issue by DanielLEVY25021961** [pmd/pmd-eclipse-plugin#104] opened 2019-06-06 18:40 UTC
Thanks so much Andreas for your quick answer.
I'm trying to share with you my **eclipseworkspace/.metadata** but I can't manage it for the moment. Could you please explain how I could share this folder ?

in Eclipse 2018-12 (4.10.0) Build id : 20181214-0600
I'm trying to install : PMD Plug-in 4.4.1.v20190602-1719
the URL for software sites is : https://dl.bintray.com/pmd/pmd-eclipse-plugin/updates/
I've already tried this one too : https://dl.bintray.com/pmd/pmd-eclipse-plugin/snapshots/updates/

After downloading the PMD Plugin, I can't configure the rules and I've got this error :
`Unable to create the selected preference page.` (please feel free to have a look on attached files)
`Could not initialize class net.sourceforge.pmd.eclipse.ui.preferences.br.PMDPreferencePage2`

I've already tried with Eclipse 2019-03, but I had exactly the same problem.

![availables software sites](https://user-images.githubusercontent.com/17048585/59057354-81785980-889a-11e9-8c9d-fc68b4bf589d.png)
![Impossible to configure the rules](https://user-images.githubusercontent.com/17048585/59057377-8a692b00-889a-11e9-8b53-050f4ed3824a.png)
![Installed_Software_1](https://user-images.githubusercontent.com/17048585/59057388-8fc67580-889a-11e9-9014-0100b038ac15.png)
![Installed_Software_2](https://user-images.githubusercontent.com/17048585/59057397-948b2980-889a-11e9-87ca-0f8fc213696d.png)
![unable_to_create_the_selected_preference_page-Window](https://user-images.githubusercontent.com/17048585/59057409-994fdd80-889a-11e9-8036-e39f46d3eaa3.png)

**Comment by DanielLEVY25021961** [comment] 2019-06-06 19:42
Hi Andreas,
can you log to this repository 👍 
https://github.com/DanielLEVY25021961/metadata.git

I tried to put in it all the stuff going on with PMD from my .metadata

Please let me know if you need something else
Best regards
Daniel

**Comment by adangel** [comment] 2019-06-07 08:04
Thanks for sharing your preferences. Unfortunately I can't reproduce the problem.
If you look at the Error Log (Window, Show View, Error Log), you should see the error "Unable to create selected preference page.". Could you please double click on it and copy the stacktrace here?

**Comment by adangel** [comment] 2019-06-07 08:25
Oh, and another question: Do you know from which version you have updated to 4.4.1? You should see this in the Installation Details in the tab "Installation History".

**Comment by DanielLEVY25021961** [comment] 2019-06-07 10:57
Hi Andreas,
Here is the stacktrace you've been asking for :

`java.lang.NoClassDefFoundError: Could not initialize class net.sourceforge.pmd.eclipse.ui.preferences.br.PMDPreferencePage2
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:206)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:934)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.ui.internal.WorkbenchPlugin.createExtension(WorkbenchPlugin.java:284)
	at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceNode.createPage(WorkbenchPreferenceNode.java:51)
	at org.eclipse.jface.preference.PreferenceDialog.createPage(PreferenceDialog.java:1279)
	at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.createPage(FilteredPreferenceDialog.java:361)
	at org.eclipse.jface.preference.PreferenceDialog.showPage(PreferenceDialog.java:1166)
	at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.showPage(FilteredPreferenceDialog.java:675)
	at org.eclipse.jface.preference.PreferenceDialog$5.lambda$0(PreferenceDialog.java:660)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
	at org.eclipse.jface.preference.PreferenceDialog$5.selectionChanged(PreferenceDialog.java:657)
	at org.eclipse.jface.viewers.StructuredViewer$3.run(StructuredViewer.java:874)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:47)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:176)
	at org.eclipse.jface.viewers.StructuredViewer.firePostSelectionChanged(StructuredViewer.java:871)
	at org.eclipse.jface.viewers.StructuredViewer.setSelection(StructuredViewer.java:1720)
	at org.eclipse.jface.viewers.TreeViewer.setSelection(TreeViewer.java:1084)
	at org.eclipse.jface.preference.PreferenceDialog.selectSavedItem(PreferenceDialog.java:990)
	at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.selectSavedItem(FilteredPreferenceDialog.java:727)
	at org.eclipse.jface.preference.PreferenceDialog.lambda$0(PreferenceDialog.java:350)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
	at org.eclipse.jface.preference.PreferenceDialog.createContents(PreferenceDialog.java:347)
	at org.eclipse.jface.window.Window.create(Window.java:430)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1099)
	at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.createDialogOn(WorkbenchPreferenceDialog.java:105)
	at org.eclipse.ui.dialogs.PreferencesUtil.createPreferenceDialogOn(PreferencesUtil.java:195)
	at org.eclipse.ui.dialogs.PreferencesUtil.createPreferenceDialogOn(PreferencesUtil.java:119)
	at org.eclipse.ui.internal.OpenPreferencesAction.run(OpenPreferencesAction.java:65)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:476)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:568)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:400)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3944)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3547)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
`
the previous installation was : 
    PMD Plug-in	4.3.1.v20190517-2220

![Eclipse IDE CURRENT Installation Details](https://user-images.githubusercontent.com/17048585/59099554-afee4700-8923-11e9-9111-bdf5b56eb246.png)
![Eclipse IDE PREVIOUS Installation Details](https://user-images.githubusercontent.com/17048585/59099562-b54b9180-8923-11e9-8bc8-acd25a7d4f0d.png)

**Comment by DanielLEVY25021961** [comment] 2019-06-07 13:10
I can see there is also an **Unhandled event loop exception**

`java.lang.NoClassDefFoundError: Could not initialize class net.sourceforge.pmd.eclipse.ui.priority.PriorityDescriptorCache
	at net.sourceforge.pmd.eclipse.ui.PMDMarkerImageProvider.getManagedImage(PMDMarkerImageProvider.java:43)
	at org.eclipse.ui.texteditor.DefaultMarkerAnnotationAccess.getImage(DefaultMarkerAnnotationAccess.java:374)
	at org.eclipse.ui.texteditor.DefaultMarkerAnnotationAccess.paint(DefaultMarkerAnnotationAccess.java:268)
	at org.eclipse.jface.text.source.AnnotationRulerColumn.doPaint1(AnnotationRulerColumn.java:812)
	at org.eclipse.jface.text.source.AnnotationRulerColumn.doubleBufferPaint(AnnotationRulerColumn.java:538)
	at org.eclipse.jface.text.source.AnnotationRulerColumn.lambda$1(AnnotationRulerColumn.java:266)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:234)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4131)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1064)
	at org.eclipse.swt.widgets.Composite.WM_PAINT(Composite.java:1655)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4825)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:348)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4778)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3545)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
`

**Comment by adangel** [comment] 2019-06-07 13:19
Hm... the stacktrace is strange:

"java.lang.NoClassDefFoundError: Could not initialize class net.sourceforge.pmd.eclipse.ui.preferences.br.PMDPreferencePage2" usually means, that either PMDPreferencePage2 or a class, that is used by PMDPreferencePage2, could not be found.
Is there any other error message (eg. a "caused by" stacktrace)?

The same would be with `java.lang.NoClassDefFoundError: Could not initialize class net.sourceforge.pmd.eclipse.ui.priority.PriorityDescriptorCache`.

Either way, this indicates that the installation of the plugin failed or is incomplete - since all the classes that are needed, are contained in the plugin. I've tried to reproduce the problem, in case in appeared while updating from 4.3.1 to 4.4.1, but no luck.

I suggest to uninstall the plugin and install it again and see, if that works....
(also double-check that you are not running out of disk space while installing the plugin)

**Comment by DanielLEVY25021961** [comment] 2019-06-07 17:52
Hourrah !!!
Dear Andreas, I could manage the issue by re-installing totally PMD PLUGIN and cleaning first the .p2 Directory.
I attached a Microsoft Word document showing what I did.
I did'nt figure out what was causing that mess. Maybe the oldest version of the PMD PLUGIN in .p2 Directory ?

Thanks a lot

I'm going to open a new post because I would like to know exactly how to export my PMD rules Configuration on an Eclipse (same version) installed on a second machine. I can't manage it by exporting the ruleset (xml file).

I 'll let you close this post if you want.

Best regards,
Daniel

[Installation du Plugin PMD dans Eclipse.docx](https://github.com/pmd/pmd-eclipse-plugin/files/3267080/Installation.du.Plugin.PMD.dans.Eclipse.docx)

**Comment by adangel** [comment] 2019-06-11 19:04
Awesome, that it works now. I'm closing this issue then.

> I Used the URL : https://dl.bintray.com/pmd/pmd-eclipse-plugin/snapshots/updates/ to reach the 4.4.1 version
> It appears that : https://dl.bintray.com/pmd/pmd-eclipse-plugin/updates/ point towards the 4.4.0 version ???

This is correct: The first one contains SNAPSHOTs, which are the latest builds from trunk. These might be work in progress.
The second update site contains only "officially" released versions.

**Closed by adangel** 2019-06-11 19:04 UTC
Labels: bug
