### ISSUE TITLE
CPD find suspect cut and paste not work

### ISSUE THREAD

**Issue by wangsirufen** [pmd/pmd-eclipse-plugin#141] opened 2021-03-08 11:31 UTC
on windows,click 'find suspect cut and paste',the CPD View is empty. But on linux, it's ok.

**Comment by wangsirufen** [comment] 2021-03-08 11:32
I think there is not enough memory. But I don't know how to solve it.

**Comment by wangsirufen** [comment] 2021-03-10 06:25
> You can set the memory for eclipse in your eclipse.ini file. Look for the line "-Xmx2048m" and change it accordingly.
> 
> CPD is running within the same JVM in which eclipse is running, so the memory could be the reason. Is your project big (many files, or big files)?
> 
> How much memory do you use under Linux?
> 
> Do you see any errors in "Error Log" in eclipse?

net.sourceforge.pmd.lang.ast.TokenMgrError: Lexical error in file OfflineVideoUtil.java at line 37, column 66.  Encountered: "-" (45), after : "\"[\\\\s~\u8def`!\u951b\u4e02#\()\u951b\u5861\\"
	at net.sourceforge.pmd.lang.java.ast.JavaParserTokenManager.getNextToken(JavaParserTokenManager.java:2393)
	at net.sourceforge.pmd.lang.java.JavaTokenManager.getNextToken(JavaTokenManager.java:25)
	
https://sourceforge.net/p/pmd/bugs/1178/

**Comment by adangel** [comment] 2021-04-22 12:35
Any chance, you could share your file `OfflineVideoUtil.java`? That way, we could investigate the bug....

**Comment by wangsirufen** [comment] 2021-05-11 06:36
> Any chance, you could share your file `OfflineVideoUtil.java`? That way, we could investigate the bug....

Ok, the contents of the document are as follows.

public class PDBTest
{
	public static String regEx="[\\s~·`!！@#￥$%^……&*（()）\\-——\\-_=+【\\[\\]】｛{}｝\\|、\\\\；;：:‘'“”\"，,《<。.》>、/？?]";
	
	public static void main(String[] args)
	{
		System.out.println("PDBTest");
	}
}

**Comment by wangsirufen** [comment] 2021-05-11 06:39
> Any chance, you could share your file `OfflineVideoUtil.java`? That way, we could investigate the bug....

Ok,the contents of the document are as follows.

public class PDBTest
{
	public static String regEx="[\\s~·`!！@#￥$%^……&*（()）\\-——\\-_=+【\\[\\]】｛{}｝\\|、\\\\；;：:‘'“”\"，,《<。.》>、/？?]";
	
	public static void main(String[] args)
	{
		System.out.println("PDBTest");
	}
}

**Comment by adangel** [comment] 2021-05-21 15:28
@wangsirufen Thanks for the code sample. Unfortunately, this code sample doesn't show any error.

I could reproduce your error message by deliberately writing invalid java code:

```
public class Foo { String a = "\-"; }
```

This produces the following error message, since `\-` is a invalid escape sequence:

```
net.sourceforge.pmd.lang.ast.TokenMgrError: Lexical error in file /home/andreas/PMD/source/pmd-it/issue-141-cpd-parse-error/src/Foo.java at line 1, column 33.  Encountered: Lexical error at line 1, column 33.  Encountered: "-" (45), after : "\"\\" (in lexical state 0)
	at net.sourceforge.pmd.lang.ast.TokenMgrError.withFileName(TokenMgrError.java:124)
	at net.sourceforge.pmd.cpd.internal.JavaCCTokenizer.tokenize(JavaCCTokenizer.java:44)
	at net.sourceforge.pmd.cpd.JavaTokenizer.tokenize(JavaTokenizer.java:42)
	at net.sourceforge.pmd.cpd.CPD.addAndThrowLexicalError(CPD.java:144)
```

I'll close this issue for now. Feel free to reopen it, if you still have this problem.

**Closed by adangel** 2021-05-21 15:28 UTC
